export interface FishingLocation {
  id: string;
  name: string;
  levelReq: number;
  description: string;
  icon: string;
  gradient: string;
  accentColor: string;
  waterType: 'still' | 'slow_current' | 'fast_current' | 'deep_water';
  weightModifier: number; // Множитель среднего веса рыбы
}

export const LOCATIONS: FishingLocation[] = [
  {
    id: 'loc_village_pond',
    name: 'Деревенский пруд',
    levelReq: 1,
    description: 'Илистое дно, кувшинки и тихая рябь воды. Идеально для старта.',
    icon: '🏡',
    gradient: 'linear-gradient(180deg, #0d321d 0%, #174229 55%, #082113 100%)',
    accentColor: '#10b981',
    waterType: 'still',
    weightModifier: 1.0,
  },
  {
    id: 'loc_old_oxbow',
    name: 'Заросшая старица',
    levelReq: 3,
    description: 'Глухой речной рукав с ряской и коряжником. Тут прячется осторожная рыба.',
    icon: '🌿',
    gradient: 'linear-gradient(180deg, #1b382b 0%, #1e4535 55%, #0b1f17 100%)',
    accentColor: '#34d399',
    waterType: 'still',
    weightModifier: 1.25,
  },
  {
    id: 'loc_forest_lake',
    name: 'Лесное озеро',
    levelReq: 6,
    description: 'Прохладная чистая вода среди сосен. Глубины скрывают красивых линей и окуней.',
    icon: '🌲',
    gradient: 'linear-gradient(180deg, #0b2f3a 0%, #134655 55%, #071f26 100%)',
    accentColor: '#06b6d4',
    waterType: 'still',
    weightModifier: 1.5,
  },
  {
    id: 'loc_quiet_river',
    name: 'Тихая речушка',
    levelReq: 9,
    description: 'Плавное течение, песчаные косы и стайки речной рыбы под обрывистым берегом.',
    icon: '🛶',
    gradient: 'linear-gradient(180deg, #113448 0%, #1b4b66 55%, #0a202d 100%)',
    accentColor: '#38bdf8',
    waterType: 'slow_current',
    weightModifier: 1.8,
  },
  {
    id: 'loc_beaver_backwater',
    name: 'Бобровый затон',
    levelReq: 12,
    description: 'Завалы из топляка и поваленных деревьев. Место обитания крупных хищников и сазанят.',
    icon: '🪵',
    gradient: 'linear-gradient(180deg, #2b2b18 0%, #3e3d23 55%, #17180c 100%)',
    accentColor: '#eab308',
    waterType: 'slow_current',
    weightModifier: 2.2,
  },
  {
    id: 'loc_wide_reach',
    name: 'Широкий плёс',
    levelReq: 15,
    description: 'Открытая речная гладь с выраженными свалами и бровками. Нужен точный дальний заброс.',
    icon: '🌊',
    gradient: 'linear-gradient(180deg, #122b49 0%, #1d436e 55%, #0a1b30 100%)',
    accentColor: '#60a5fa',
    waterType: 'slow_current',
    weightModifier: 2.7,
  },
  {
    id: 'loc_reservoir',
    name: 'Пригородное водохранилище',
    levelReq: 18,
    description: 'Огромное зеркало воды с затопленными руслами и солидными стаями крупного леща.',
    icon: '⚓',
    gradient: 'linear-gradient(180deg, #182848 0%, #243b6b 55%, #0e192f 100%)',
    accentColor: '#818cf8',
    waterType: 'deep_water',
    weightModifier: 3.3,
  },
  {
    id: 'loc_oka_river',
    name: 'Быстрая река Ока',
    levelReq: 21,
    description: 'Мощные струи, перекаты и каменистые гряды. Рыба здесь сильная и упорно сопротивляется.',
    icon: '🚤',
    gradient: 'linear-gradient(180deg, #153243 0%, #204d67 55%, #0d202b 100%)',
    accentColor: '#2dd4bf',
    waterType: 'fast_current',
    weightModifier: 4.0,
  },
  {
    id: 'loc_lower_volga',
    name: 'Нижняя Волга',
    levelReq: 24,
    description: 'Легендарное место паломничества рыбаков. Бескрайние русла и настоящие речные исполины.',
    icon: '🦅',
    gradient: 'linear-gradient(180deg, #1d2b3a 0%, #2b3f55 55%, #101923 100%)',
    accentColor: '#f59e0b',
    waterType: 'deep_water',
    weightModifier: 5.0,
  },
  {
    id: 'loc_ladoga_lake',
    name: 'Северная Ладога',
    levelReq: 27,
    description: 'Суровые гранитные скалы, холодная прозрачная бездна и трофейная северная рыба.',
    icon: '⛰️',
    gradient: 'linear-gradient(180deg, #1b2631 0%, #283747 55%, #11171d 100%)',
    accentColor: '#94a3b8',
    waterType: 'deep_water',
    weightModifier: 6.2,
  },
  {
    id: 'loc_akhtuba_pits',
    name: 'Ахтубинские ямы',
    levelReq: 30,
    description: 'Многометровые омуты с водоворотами. Место охоты тяжелых сомов и матёрых сазанов.',
    icon: '🕳️',
    gradient: 'linear-gradient(180deg, #211c27 0%, #342d3d 55%, #131017 100%)',
    accentColor: '#c084fc',
    waterType: 'deep_water',
    weightModifier: 7.8,
  },
  {
    id: 'loc_caspian_delta',
    name: 'Дельта Каспия',
    levelReq: 33,
    description: 'Раскаты, бесчисленные протоки и лотосовые поля. Здесь ловят абсолютные рекорды.',
    icon: '👑',
    gradient: 'linear-gradient(180deg, #2d2417 0%, #463723 55%, #18130b 100%)',
    accentColor: '#fbbf24',
    waterType: 'slow_current',
    weightModifier: 10.0,
  },
];

export const DEFAULT_LOCATION_ID = 'loc_village_pond';